platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZJSPhotoManager_Example' do
  pod 'ZJSPhotoManager', :path => '../'

  target 'ZJSPhotoManager_Tests' do
    inherit! :search_paths

    
  end
end
